### ISSUE TITLE
Component prevents controller test bake

### ISSUE THREAD

**Issue by jeremyharris** [cakephp/authentication#200]
If I have the component in AppController, and try baking a controller, I receive errors due to the authentication service missing from the request.

I'm not sure what the best fix is for this. Inject a fake into the request during bake, or make the AuthenticationComponent's check more lax?

<details>
<summary>Exception Stacktrace</summary>
```
Exception: The request object does not contain the required `authentication` attribute in [/vendor/cakephp/authentication/src/Controller/Component/AuthenticationComponent.php, line 59]
2018-04-16 18:29:30 Error: [Exception] The request object does not contain the required `authentication` attribute in /vendor/cakephp/authentication/src/Controller/Component/AuthenticationComponent.php on line 59
Stack Trace:
#0 /vendor/cakephp/cakephp/src/Controller/Component.php(134): Authentication\Controller\Component\AuthenticationComponent->initialize(Array)
#1 /vendor/cakephp/cakephp/src/Controller/ComponentRegistry.php(119): Cake\Controller\Component->__construct(Object(Cake\Controller\ComponentRegistry), Array)
#2 /vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(96): Cake\Controller\ComponentRegistry->_create('Authentication\\...', 'Authentication', Array)
#3 /vendor/cakephp/cakephp/src/Controller/Controller.php(324): Cake\Core\ObjectRegistry->load('Authentication....', Array)
#4 /src/Controller/AppController.php(53): Cake\Controller\Controller->loadComponent('Authentication....', Array)
#5 /vendor/cakephp/cakephp/src/Controller/Controller.php(263): App\Controller\AppController->initialize()
#6 /vendor/cakephp/bake/src/Shell/Task/TestTask.php(325): Cake\Controller\Controller->__construct(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /vendor/cakephp/bake/src/Shell/Task/TestTask.php(230): Bake\Shell\Task\TestTask->buildTestSubject('Controller', 'App\\Controller\\...')
#8 /vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(214): Bake\Shell\Task\TestTask->bake('Controller', 'QuoteRequests')
#9 /vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(163): Bake\Shell\Task\ControllerTask->bakeTest('QuoteRequests')
#10 /vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(69): Bake\Shell\Task\ControllerTask->bake('QuoteRequests')
#11 /vendor/cakephp/cakephp/src/Console/Shell.php(507): Bake\Shell\Task\ControllerTask->main('quote_requests')
#12 /vendor/cakephp/cakephp/src/Console/Shell.php(500): Cake\Console\Shell->runCommand(Array, false, Array)
#13 /vendor/cakephp/cakephp/src/Console/CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#14 /bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#15 {main}
```
</details>

**Comment by markstory** [comment]
We could move the attribute validation to a later stage of the component life-cycle. Perhaps the `startup` event?

**Comment by jeremyharris** [comment]
I think `Controller.startup` would be ok for checking the service. I can submit a PR to move the checks.
